### ISSUE TITLE
Is this the same as the old jade/runtime.js?

### ISSUE THREAD

**Issue by iancullinane** [pugjs/pug-runtime#29]
I am trying to use pug compiled templates using `pug --client file.pug` but I am unclear about how to use the runtime. I had previously used the `runtime.js` file, importing via as described on the jade api page ([http://jade-lang.com/api/](http://jade-lang.com/api/)). However in the example there is a file `jade/runtime.js` available and I do not see this in the current module.

It looks like `runtime.js` is not part of this repository or pug-runtime repository. There is this [link](https://raw.githubusercontent.com/pugjs/pug/1.11.0/runtime.js) but I am not seeing anything in the files downloaded through npm. Is there something that needs to be compiled?

The new page for pug says " It is recommended that you pre-compile your pug templates to JavaScript and then just use the runtime.js library on the client." but I am unsure what I am using or how to use it. Can this module be loaded via html, or browserify? I achieved what I want by copying the link but I would rather use a file coming from some kind of source control. Maybe I am missing something?

**Comment by TimothyGu** [comment]
Okay, here's the status of the new runtime.
1. First and foremost, Pug is not ready for production use. It is still in the stage of alpha.
2. We have rewritten and optimized the old runtime.js and compatibility is not guaranteed.
3. By default, you **do not** need to include a separate runtime any more since we now inline the runtime automatically when you use `compileClient` or `compileClientWithDependenciesTracked`.
4. We do recognize that this choice means that there can be bloat when you have multiple templates, all having their own copy of the runtime. To combat this, you could set `inlineRuntimeFunctions` option to `false` when compiling.
5. If you do so, just make sure that if you do, the exported functions in https://github.com/pugjs/pug-runtime/blob/master/index.js are available as `pug` when the template is used. We do not supply a browserified file any more because that process is a bit too opinionated to fit into the many workflow tools users use.

Hope this helps.

**Comment by iancullinane** [comment]
Thank you this is very helpful.
